# Generated by Django 4.1 on 2023-07-17 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_imageupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("image", models.ImageField(null=True, upload_to="images/")),
                ("caption", models.CharField(max_length=50)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.article"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="ImageUpload",),
    ]
